### ISSUE TITLE
Crashing Node Red

### ISSUE THREAD

**Issue by beccsjb** [igdr/node-red-contrib-xiaomi-smart-devices#13]
Latest version seems to be crashing node-red entirely, causing a restart Loop..

3 May 23:24:09 - [red] Uncaught Exception:
3 May 23:24:09 - Error: addMembership EINVAL
    at _errnoException (util.js:1022:11)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
3 May 23:24:13 - [info]

I then have to go in edit the flow jason file, disable the flow that contains the gateway node, re start node red. Delete the gateway node, enable the flow and node red then runs fine again.

Anyone else having similar issues with the latest release?

**Comment by igdr** [comment]
I'll check it this weekend

**Comment by beccsjb** [comment]
Is it possible to install the previous version again? I've got alot of automation hanging off this node.

If so, how?

**Comment by igdr** [comment]
"node-red-contrib-xiaomi-smart-devices": "1.0.15"

**Comment by beccsjb** [comment]
lol i usually use Palette Manager. No idea how to do that.

**Comment by beccsjb** [comment]
I may have figured it out :) just restarting node-red

**Comment by beccsjb** [comment]
i edited the package.json file with nano. Basically, removed 1.0.16 and replaced with 1.0.15 and restarted node red, but no change. Node red still says the xiaomi version is 1.0.16

**Comment by igdr** [comment]
#12
