### ISSUE TITLE
How do I find the SID of my gateway ?

### ISSUE THREAD

**Issue by realjax** [igdr/node-red-contrib-xiaomi-smart-devices#15]
See title..

Edit:  I managed to find it because I happened to jot it down somewhere but if I hadn't (and new users too I guess) I'd have no clue.

**Comment by igdr** [comment]
![image](https://user-images.githubusercontent.com/4249152/57586941-f2c82500-7505-11e9-9d7e-230d13389b53.png)

When the gateway node connects to the network (you can leave SID empty when configuring), SID automatically appears in the node hint.

**Comment by igdr** [comment]
I see this might be simplified a bit - remove this field from the configuration and set automatically when receiving heartbeats from the Xiaomi Gateway.

**Comment by realjax** [comment]
Ah, I think it complained about not being configured correctly when I did leave it emptyt?  Not sure.

**Comment by igdr** [comment]
I am going to remove SID from gateway config - so it would be confusing users

**Comment by igdr** [comment]
I removed SID from the gateway config, now it is assigned automatically when the gateway initializes.
