### ISSUE TITLE
Gateway config not working

### ISSUE THREAD

**Issue by realjax** [igdr/node-red-contrib-xiaomi-smart-devices#16]
I have a new gateway configured. Set it to the correct key and host ( ip address in my case) and port ( 9898) but a new gateway node won't connect.  nothing is in the logs.

**Comment by igdr** [comment]
could you leave these fields empty and try? Defaults values will be set (224.0.0.50: 9898)

**Comment by igdr** [comment]
I modify the gateway node a bit, now IP address is real address in your network like you wrote. 
It is not a required field, cause gateway connects to a multicast address in your network 224.0.0.50 according to the gateway development documentation
