### ISSUE TITLE
Need examples.flow

### ISSUE THREAD

**Issue by andreypopov** [igdr/node-red-contrib-xiaomi-smart-devices#17]
How to play sound on gateway? Where is the list of commands

**Comment by igdr** [comment]
Here is my example: 
![image](https://user-images.githubusercontent.com/4249152/57848936-be44b980-77e2-11e9-960b-c94b9cc48b29.png)

**Change color:**

```
let cmd = {
 "rgb": 440038609
}
msg.payload = cmd;
return msg;
```

**Play some sound:**
```
let cmd = {
 "mid": 1, 
 "vol": 27
}
msg.payload = cmd;
return msg;
```

**Comment by igdr** [comment]
Documentation for the gateway node has been updated in v2.0.4 with examples.

**Comment by alexsahka** [comment]
Could you provide a link to the Documentation?
