### ISSUE TITLE
guidelines to add switch?

### ISSUE THREAD

**Issue by kuradi** [igdr/node-red-contrib-xiaomi-smart-devices#22]
may i ask some guidelines how to add switch?
![switch](https://user-images.githubusercontent.com/31483391/61078427-433a0100-a429-11e9-9356-1a69aeb290db.jpg)
adding gateway and name seems not working... and from dropdown menu is not possible to choose anything...

**Comment by igdr** [comment]
Hi, what version do you use?, from the screenshot, I see that it is version 1.x.
The first step you should configure the gateway and add devices to the device list. After that, you can choose the device in the dropdown.

Or install new version 2.x, this version is pretty easy to configure, just configure the gateway and set SID to the corresponded node, in your case it would be switch.

**Comment by kuradi** [comment]
i would say i have ver2 and i can configure all other nodes - temp, water without problems... only problematic is switch. 

for example adding motion...
![motion](https://user-images.githubusercontent.com/31483391/61079246-1b4b9d00-a42b-11e9-9981-288d566d887f.jpg)

**Comment by igdr** [comment]
let me check

**Comment by kuradi** [comment]
2.0.4 is version

**Comment by igdr** [comment]
this is a really interesting issue, cause I couldn't find such node, it looks like from version 1
![image](https://user-images.githubusercontent.com/4249152/61081599-41277080-a430-11e9-9890-28b8a5773248.png)

In a new version, it is called "The Xiaomi Button node".
It might be some cache if you updated from the version 1

**Comment by kuradi** [comment]
strange :) on the left side i see this 
![xiaomi](https://user-images.githubusercontent.com/31483391/61081916-0c67e900-a431-11e9-8bd5-0ebd120840c0.jpg)

how can i fix it?

**Comment by kuradi** [comment]
fixed! :)

**Comment by igdr** [comment]
:)
