### ISSUE TITLE
Sometimes Not Connecting and Not Receiving Data

### ISSUE THREAD

**Issue by komputerboy** [igdr/node-red-contrib-xiaomi-smart-devices#33]
I am able to connect my xiaomi gateway device to node-red. But, I have problem that sometimes xiaomi gateway node-red is not connected and also it is not receiving the data. But, sometimes it also work. Could you please resolve it?

I am using latest firmware in my xiaomi gateway.

Thank you

**Comment by mreyad** [comment]
I have same problem. The version I am using is 2.0.4 and node red 1.0.5

**Comment by realjax** [comment]
same here.
