### ISSUE TITLE
Brightness Gateway

### ISSUE THREAD

**Issue by KL-AU-S** [igdr/node-red-contrib-xiaomi-smart-devices#5]
Hi,
is it possible to set the brightness of the gateway-light. In the xiaomi-app i can do this?

Kind regards 
Klaus

**Comment by igdr** [comment]
Hi, take a look here https://github.com/igdr/node-red-contrib-xiaomi-smart-devices/issues/3

Also here is a great article about how to use this package:
https://notenoughtech.com/home-automation/nodered-home-automation/xiaomi-gateway-in-nodered/

**Comment by KL-AU-S** [comment]
Hi, these references are not new for me but i can´t see anything about brightness. What´s the parameter for it? I tried it with  the following command:
{"cmd": "write", "model": "gateway",	"sid": "7811dcdeaf46", "short_id": 0, "key": "7", "data": {"rgb": 4286578695,  "dimmer": 3} }
But still this do not set the brightness. What is the correct command?
Another Question, for what is this key: 7 or key:8 parameter?

Kind regards
Klaus

**Comment by igdr** [comment]
I tried doing as in the example, and find out that it works but without changing AARRGGBB -> RRGGBBAA 
![image](https://user-images.githubusercontent.com/4249152/53122693-e1532a80-355f-11e9-9b92-d86fa8c4a509.png)

Here is the solution which is worked for me:

`let cmd = {
  "cmd": "write",
  "sid": "34ce008c1100",
  "model": "gateway",
  "data": {"rgb": 440038609}
}
msg.payload = cmd;
return msg;`

**Comment by KL-AU-S** [comment]
Now it works for me too. 
Thanks and kind regards KLaus

**Comment by igdr** [comment]
You are welcome
