### ISSUE TITLE
Cant deploy two gateway nodes

### ISSUE THREAD

**Issue by realjax** [igdr/node-red-contrib-xiaomi-smart-devices#6]
My Nodered is in a bootloop it seems. Caused by this:

> ...
> UDP socket listening on 0.0.0.0:9898
> 9 Mar 16:10:47 - [red] Uncaught Exception:
> 9 Mar 16:10:47 - Error: bind EADDRINUSE 0.0.0.0:9898
> nodered.service: Main process exited, code=exited, status=1/FAILURE
> nodered.service: Unit entered failed state.
> nodered.service: Failed with result 'exit-code'.
> ....

**Comment by realjax** [comment]
If you deploy a flow that has a second gateway node instance this error occurs.

**Comment by Sojborg** [comment]
I just updated to the lastest version and now i get the same error. Worked fine before upgrading.

I get the error by just adding one gateway to a flow.

**Comment by realjax** [comment]
Guess it does need this after all :D  
`dgram.createSocket({type: 'udp4', reuseAddr: true});`

**Comment by igdr** [comment]
the new version is 1.0.12
