### ISSUE TITLE
two gateways

### ISSUE THREAD

**Issue by bednim** [igdr/node-red-contrib-xiaomi-smart-devices#7]
hi there, added two gateways with two different ips/keys, added two different sensors and connected debug nodes to them. seems to work fine but for example motion from one gateway is outputted on debug node from both gateways. is this normal behaviour?

sidenote - is it possible that LUX and MOTION could be outputted on one message? this is of course in regards to motion sensor.

thank you

**Comment by igdr** [comment]
Hi, of course, it is not normal behavior. The problem is the Gateway component doesn't work with two gateways and more. I would be appreciated if you added such functionality to the Gateway component and created a new pull request.
