### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by realjax** [igdr/node-red-contrib-xiaomi-smart-devices#9]
Hi, 

I've opened a new pull request. Can you take a look at it?  Btw, if you have no desire to maintain this repo anymore then I am prepared to take over.

cheers.

**Comment by igdr** [comment]
Hi, thanks, I didn't have free time these days. I merged your pull request - version 1.0.13

**Comment by realjax** [comment]
Cool! Thanks.

Igor <notifications@github.com> schreef op 31 maart 2019 15:39:58 CEST:
